---
- name: Uninstall release via Helm
  ansible.builtin.shell:
    set -o errexit
    set -o pipefail
    set -o nounset

    helm uninstall {{ traefik_release_name }} --namespace {{ traefik_namespace }}

    exit 0
  run_once: true
  delegate_to: "{{ traefik_delegate_to }}"
  args:
    executable: "/bin/bash"

- name: Remove repository via Helm
  shell:
    set -o errexit
    set -o pipefail
    set -o nounset

    helm repo remove {{ traefik_repo_name }}

    exit 0
  run_once: true
  delegate_to: "{{ traefik_delegate_to }}"
  args:
    executable: "/bin/bash"

- name: Delete namespace
  kubernetes.core.k8s:
    name: "{{ traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true
