---
- name: Uninstall release via Helm
  kubernetes.core.helm:
    name: "{{ traefik_release_name }}"
    release_namespace: "{{ traefik_namespace }}"
    state: absent
  run_once: true
  delegate_to: "{{ traefik_delegate_to }}"

- name: Remove repository via Helm
  kubernetes.core.helm:
    name: "{{ traefik_repo_name }}"
    purge: "yes"
  run_once: true
  delegate_to: "{{ traefik_delegate_to }}"

- name: Delete namespace
  kubernetes.core.k8s:
    name: "{{ traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true
