---
- name: Uninstall release via Helm
  kubernetes.core.helm:
    name: "{{ traefik_release_name }}"
    release_namespace: "{{ traefik_namespace }}"
    state: absent
  run_once: true
  delegate_to: "{{ traefik_delegate_to }}"
  register: traefik__helm_show_uninstall_release

- name: Uninstall release via Helm (helm command executed)
  ansible.builtin.debug:
    var: traefik__helm_show_uninstall_release.command
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true
  when:
    - traefik__helm_show_uninstall_release is defined
    - traefik__helm_show_uninstall_release.command is defined
    - traefik_helm_show_commands

- name: Remove repository via Helm
  kubernetes.core.helm_repository:
    name: "{{ traefik_repo_name }}"
    repo_state: absent
  run_once: true
  delegate_to: "{{ traefik_delegate_to }}"
  register: traefik__helm_show_remove_repository

- name: Remove repository via Helm (helm command executed)
  ansible.builtin.debug:
    var: traefik__helm_show_remove_repository.command
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true
  when:
    - traefik__helm_show_remove_repository is defined
    - traefik__helm_show_remove_repository.command is defined
    - traefik_helm_show_commands

- name: Delete namespace
  kubernetes.core.k8s:
    name: "{{ traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true
