---
- name: Ensure namespace
  k8s:
    name: "{{ traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  delegate_to: 127.0.0.1
  run_once: true

- name: Register if Helm repository is installed
  command: helm search repo {{ traefik_chart_name }} -n {{ traefik_namespace }}
  register: traefik_repo_installed
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true

- name: Add Helm repository
  command: helm repo add {{ traefik_repo_name }} {{ traefik_chart_url }}
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true
  when: "traefik_repo_installed.stdout.find(traefik_chart_name) == -1"

- name: Update local Helm chart repository cache
  command: helm repo update -n {{ traefik_namespace }}
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true
