---
- name: Ensure namespace
  k8s:
    name: "{{ traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true

- name: Register if Helm repository is installed
  kubernetes.core.helm_info:
    name: traefik
    release_namespace: traefik
    release_state:
      - all
  register: traefik_repo_installed
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true

- name: Add Helm repository
  kubernetes.core.helm_repository:
    name: "{{ traefik_repo_name }}"
    repo_url: "{{ traefik_chart_url }}"
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true
  when: "traefik_repo_installed.status is not defined"

- name: Update local Helm chart repository cache
  kubernetes.core.helm:
    name: "{{ traefik_repo_name }}"
    namespace: "{{ traefik_namespace }}"
    state: absent
    update_repo_cache: true
  delegate_to: "{{ traefik_delegate_to }}"
  run_once: true
