---
- name: Include prerequisites
  ansible.builtin.include_tasks:
    file: "tasks/prerequisites.yml"

- name: Render values
  block:
    - name: Install Traefik CRDs
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', item) | from_yaml }}"
      with_fileglob:
        - "crds/*.yaml"
      delegate_to: "{{ traefik_delegate_to }}"
      run_once: true
      when:
        - traefik_install_crds

    - name: Create temporary file for Helm values
      ansible.builtin.tempfile:
        state: file
        suffix: traefik_values
      delegate_to: "{{ traefik_delegate_to }}"
      run_once: true
      register: traefik_values_tmp_file

    - name: Select values file for Helm template
      ansible.builtin.template:
        src: "{{ lookup('first_found', params) }}"
        dest: "{{ traefik_values_tmp_file.path }}"
        mode: 0600
      delegate_to: "{{ traefik_delegate_to }}"
      run_once: true
      vars:
        params:
          files:
            - values.yml.j2
            - values.yaml.j2
            - traefik_values_default.yml.j2
          paths:
            - "{{ traefik_chart_values_directory }}"
            - templates

    - name: Upgrade Helm chart
      kubernetes.core.helm:
        name: "{{ traefik_release_name }}"
        chart_ref: "{{ traefik_chart_name }}"
        chart_version: "{{ traefik_chart_version }}"
        release_namespace: "{{ traefik_namespace }}"
        create_namespace: false
        update_repo_cache: true
        values_files:
          - "{{ traefik_values_tmp_file.path }}"
      run_once: true
      delegate_to: "{{ traefik_delegate_to }}"
      register: traefik__helm_upgrade_chart

    - name: Upgrade Helm chart (helm command executed)
      ansible.builtin.debug:
        var: traefik__helm_upgrade_chart.command
      delegate_to: "{{ traefik_delegate_to }}"
      run_once: true
      when:
        - traefik__helm_upgrade_chart is defined
        - traefik__helm_upgrade_chart.command is defined
        - traefik_helm_show_commands

    - name: Delete temporary file for Helm values
      ansible.builtin.file:
        path: "{{ traefik_values_tmp_file.path }}"
        state: absent
      run_once: true
      delegate_to: "{{ traefik_delegate_to }}"
      when:
        - traefik_values_tmp_file.path is defined

  rescue:
    - name: Delete temporary file for Helm values
      ansible.builtin.file:
        path: "{{ traefik_values_tmp_file.path }}"
        state: absent
      run_once: true
      delegate_to: "{{ traefik_delegate_to }}"
      when:
        - traefik_values_tmp_file.path is defined
