---
# Copyright (C) 2024 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Gather facts
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Populate Ansible hostVars
      ansible.builtin.setup:

- name: Setup Traefik
  hosts: k8s_worker
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
  tasks:
    - name: Include Traefik role
      ansible.builtin.include_role:
        name: githubixx.traefik_kubernetes
      vars:
        #
        # Install
        # action: "install"
        #
        # Upgrade
        # action: "upgrade"
        #
        # Render Helm chart only
        action: "template"
        #
        # Delete all resources
        # action: "delete"
