---
# Copyright (C) 2024 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Verify setup
  hosts: test-assets
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
  tasks:
    - name: Fetch Traefik DaemonSet information
      kubernetes.core.k8s_info:
        api_version: v1
        kind: DaemonSet
        name: traefik
        namespace: traefik
      register: traefik__daemonset_info

    - name: Print DaemonSet JSON blob
      ansible.builtin.debug:
        var: traefik__daemonset_info
      when: ansible_verbosity > 1

    - name: There should be a DaemonSet called traefik
      ansible.builtin.assert:
        that:
          - traefik__daemonset_info.resources[0].metadata.name == "traefik"

    - name: There should be at least one Traefik pod running
      ansible.builtin.assert:
        that:
          - (traefik__daemonset_info.resources[0].status.numberReady | default(0) | int) >= 1

    - name: Create test namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: test
        state: present

    - name: Create test Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'test-deployment.yml') | from_yaml }}"
        wait: yes
        wait_condition:
          type: Available
          status: True

    - name: Create test Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'test-service.yml') | from_yaml }}"

    - name: Create test IngressRoute - Traefik v2 syntax
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'test-ingressroute-v2.yml') | from_yaml }}"

    - name: Get homepage from test deployment - www.example-v2.com
      ansible.builtin.get_url:
        url: "http://10.10.10.200"
        dest: "/dev/null"
        headers:
          Host: www.example-v2.com
      register: test__check_url

    - name: Request to test-v2 IngressRoute should return HTTP 200 
      ansible.builtin.assert:
        that:
          - (test__check_url.status_code | default(999) | int) == 200

    - name: Delete test IngressRoute - Traefik v2 syntax
      kubernetes.core.k8s:
        name: "test-v2"
        api_version: "traefik.containo.us/v1alpha1"
        kind: "IngressRoute"
        namespace: "test"
        state: absent

    - name: Delete test Service and Deployment
      kubernetes.core.k8s:
        name: "test"
        api_version: "v1"
        kind: "{{ k8s_resource }}"
        namespace: "test"
        state: absent
      loop:
        - Service
        - Deployment
      loop_control:
        loop_var: k8s_resource
