---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Verify setup
  hosts: test-assets
  tasks:
    - name: Fetch Traefik DaemonSet information
      k8s_info:
        api_version: v1
        kind: DaemonSet
        name: traefik
        namespace: traefik
      register: traefik__daemonset_info

    - name: Print DaemonSet JSON blob
      ansible.builtin.debug:
        var: traefik__daemonset_info
      when: ansible_verbosity > 1

    - name: There should be a DaemonSet called traefik
      ansible.builtin.assert:
        that:
          - traefik__daemonset_info.resources[0].metadata.name == "traefik"

    - name: There should be at least one Traefik pod running
      ansible.builtin.assert:
        that:
          - (traefik__daemonset_info.resources[0].status.numberReady | default(0) | int) >= 1

    - name: Get homepage from Traefik
      ansible.builtin.get_url:
        url: "http://10.10.10.100"
        dest: "/dev/null"
      register: traefik__check_url
      ignore_errors: true

    - name: Request to Traefik should return HTTP 404
      ansible.builtin.assert:
        that:
          - (traefik__check_url.status_code | default(999) | int) == 404
